### PR TITLE
Return URL or Callback for Quick Updating

### PR DESCRIPTION
**Pull request by jpoehnelt**
Sometimes it may be nice to quickly mock multiple responses within a single test with only minor changes in the response. This allows that to happen.

```
fake = responses.add(responses.GET, url, body="something", status=200)
r = requests.get(url)
assert r.status_code == fake['status']

fake['status'] = 400
r = requests.get(url)
assert r.status_code == fake['status'] # 400

fake['body'] = "something else"
r = requests.get(url)
assert r.text == fake['body'] # "something else"
```

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
@markstory 
I am not confident that we want to promote such functionality. 
I would rather create a `Response` object and add it multiple times, modifying attributes each time
https://github.com/getsentry/responses/blob/f6c71ae70aa1645f6fdda4eb236042109c225e2e/responses/test_responses.py#L1934


your thoughts?

**Comment by markstory** [comment]
>  I would rather create a Response object and add it multiple times, modifying attributes each time

I agree. Having mutable objects come out of responses increases the chance for temporal coupling in tests. I also prefer the flow where responses are created in the test, and then attached to response mocks.

**Comment by beliaev-maksim** [comment]
@markstory
OK, then propose to close the PR

**Comment by markstory** [comment]
Thanks for taking the time to put this together @jpoehnelt. I don't want to encourage user code to mutating the response objects. If you need this behavior you can create your own response instances and attach them to responses similar to the test case example linked to earlier in the issue.

**Pull request closed without merging**
