### PR TITLE
remove readonly properties

### PR DESCRIPTION
**Pull request by beliaev-maksim**
currently we expose 2 attributes, users may think that changing them will affect something, but it is not
best example to show:

```python
import responses

print(responses.assert_all_requests_are_fired)
responses.assert_all_requests_are_fired = True
print(responses.assert_all_requests_are_fired)
print(responses.mock.assert_all_requests_are_fired)
```

produces
```python
False
True
False
```

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
tests fail, #495 should fix it

**Comment by markstory** [comment]
I'm concerned that we'll break user-land code by taking these away. Given the impacts of past clean up changes, we've seen that user-land code is using several internals (eg. `_is_string`). Perhaps we should add a property wrapper for these and emit deprecation warnings?

**Comment by beliaev-maksim** [comment]
also a valid argument

any ideas how to create a property without a class instance?
since now it is just a variable in the module, eg `responses.assert_all_requests_are_fired`

**Comment by aburgel** [comment]
> any ideas how to create a property without a class instance?

you can do something like this to deprecate these module attributes: https://www.python.org/dev/peps/pep-0562/

**Comment by beliaev-maksim** [comment]
> > any ideas how to create a property without a class instance?
> 
> you can do something like this to deprecate these module attributes: https://www.python.org/dev/peps/pep-0562/

Sounds like an idea, I will try it
Thanks

**Comment by beliaev-maksim** [comment]
@markstory 
can you please review?

**Comment by beliaev-maksim** [comment]
@markstory 
merge conflicts are resolved

**Pull request merged**
