### PR TITLE
Allow the fragment identifier to be ignored when matching urls.

### PR DESCRIPTION
**Pull request by zamzterz**
Defaults to not forcing match of the fragment identifier, similar to the handling of querystrings.

### CODE REVIEW

**Comment by dcramer** [comment]
I'm not against the idea of this change, but I dont know if "fargment identifier" is really a common term. This is treating a fragment as if its a query string (which I realize, once upon a time, was common). For things like this I definitely would prefer we just create a better way of handling requests so you can specify a callback to deal w/ validation.

**Comment by rebeckag** [comment]
"Fragment" is probably the most common term, but since it's "querystring" (instead of just "query") I just chose "fragment identifier" [based on Wikipedia](https://en.wikipedia.org/wiki/Fragment_identifier). I have no issues with changing the naming to either "fragment" or something else if you have any suggestions.

I agree with your idea about a more general way of delegating the request validation, but my use case is actually to be able to ignore the fragment. And since that functionality is provided for query strings it would be nice, for consistency, if the same behaviour is implemented for fragments by default (without needing to provide my own custom validation callback which just ignores the fragment, but needs to otherwise match the url).

**Comment by beliaev-maksim** [comment]
@markstory 
please close this PR

**Comment by markstory** [comment]
Closing as fragment matching has been added as part of the matchers module.

**Pull request closed without merging**
