### PR TITLE
Update changelog for 0.10.0 and 0.10.1

### PR DESCRIPTION
**Pull request by adamchainz**
This was missed, I couldn't tell what was changing as I was upgrading - some of my tests broke - so I had to read the git log to figure this out. THis will help future travellers.

### CODE REVIEW

**Comment by markstory** [comment]
What broke in your tests?

**Comment by adamchainz** [comment]
`biscuits` wasn't installing because I compile my test requirements on Python 2 for both Python 2 and 3 - a bit of a hack I know, but in practicality this is the first time it has been a problem, normally there are just Python 2-only requirements (across like 20 projects). https://github.com/adamchainz/ec2-metadata/pull/96/files .

Not `responses`' fault, but on the other hand I did switch to `requests-mock` after making these PR's to `responses` and seeing how it works, and re-researching `requests-mock`. 🙈

**Comment by markstory** [comment]
Thanks for the additional context @adamchainz I'll look for another way to parse set-cookie headers that doesn't introduce py3 only dependencies.

**Comment by adamchainz** [comment]
There's `http.cookies` in the standard library

**Pull request merged**
