### PR TITLE
Don't install mock on Python 3.3 +

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
Coverage 4.0 drops support for Python 3.2

**Comment by graingert** [comment]
this build has got stuck and is blocking all my Travis builds, can you kill it for me? https://travis-ci.org/getsentry/responses/builds/84707373

**Comment by graingert** [comment]
Thanks, it's cancelled now, If you also kill all my other builds except for https://travis-ci.org/getsentry/responses/builds/84711057 that would be awesome too :D

**Comment by graingert** [comment]
@dcramer any chance of getting this pulled in?

**Comment by dcramer** [comment]
Thanks!

**Comment by graingert** [comment]
@dcramer any chance of a release of this? Thanks!

**Comment by dcramer** [comment]
0.5.0 is on pypi


On October 14, 2015 at 2:13:09 AM, Thomas Grainger (notifications@github.com) wrote:

@dcramer any chance of a release of this? Thanks!

**Comment by graingert** [comment]
Nice :D

**Pull request merged**
