### PR TITLE
Added __title__, __description__, and __version__ to responses.

### PR DESCRIPTION
**Pull request by hramezani**
Fixes https://github.com/getsentry/responses/issues/255

### CODE REVIEW

**Comment by dcramer** [comment]
What is the purpose of these?

You can get the version of libraries via `pkg_resources` already, and afaik the other attributes aren't used?

**Comment by hramezani** [comment]
>What is the purpose of these?

Some libraries like `requests`, `django`, `flask`, ... has a `__version__` or `get_version()` or both to fetch the library version.
Also, it can be a starting point to improve the library structure and move `responses.py` to a directory and maybe split it to multiple files.(to make it more readable)

> You can get the version of libraries via `pkg_resources` already, and afaik the other attributes aren't used?
Yes, you are right. 
> afaik the other attributes aren't used?
Yes, we can remove them. TBH, I just added them because they are in `requests` library.

BTW, If this change does not make sense to you we can close the PR.

**Comment by dcramer** [comment]
I've used ``__version__`` in the past, but its another point that has to be continuously updated and I feel like it has less values these days.

That said, I've never used any of the others in the hundreds of libraries I've released. I don't know that we need them, and I'd encourage to us to avoid breaking up the file unless it makes sense (because its gotten unwieldy). I certainly don't maintain things anymore, but the single file has the advantage of being easy to understand scope and see how everything works.

Just my two cents.

**Comment by hramezani** [comment]
@dcramer Thanks for the explanation.
I removed the ` __title__` and `__description__`.
Again, If it does not make sense to you we can close the PR and also issue #255.

**Pull request closed without merging**
