### PR TITLE
responses registry - alternative implementation

### PR DESCRIPTION
**Pull request by carloshorn**
Last week, I ran again into a situation, where a custom registry could have made things easier. I had added my responses in order, and all I wanted was to pop one after the other. The problem was that some of the requests had queries and others not but they were sent to the same endpoint. I could fix it by setting `match_querystring`, but a strict pop one after the other registry would have made things more intuitive.

@beliaev-maksim has opened #416 to implement this feature which I proposed at the end of #411.
Here, I want to thank @beliaev-maksim for his effort in #416 and the fruitful discussions on this feature. However, I got the impression that his implementation might add complexity that keeps you from merging. So I decided to propose an alternative implementation which does not touch the public interface of the module and only focuses on the implementation of the registry. Intentionally, this implementation does not allow the usage of this feature on the libraries default mock, due to the risk of leaking into other tests as discussed in #416. Instead, I just added the registry attribute to the public interface of the `RequestsMock` class which can be accessed and replaced by advanced users on a local instance.
For convenience, I added the most relevant registry classes into the `registries` module. Those cover the current behavior, the always start matching in insertion without popping, and the strictly pop only the next response. These scenarios are also mentioned in #311 and #376. Optimizations as proposed in #411 are left to the users, which now do not need to hack into private methods and therefore fear incompatibility of their code with newer releases.

Example usage:

```python
import responses
from responses.registries import StrictOrderRegistry

with responses.RequestsMock() as rsps:
    rsps.registry = StrictOrderRegistry()
    # add a single response for each request in requesting order
    ...
    resp.reset()
    # reset will just clear the registry which is fine, because it is only used in local instances
    # this is similar to using a response callback
    assert isinstance(rsps.registry, StrictOrderRegistry)
    assert len(rsps.registry) == 0
```

Further note that the Registry objects implement the `collections.abc.Collection` interface, which allows interactions like

```python
response in rsps.registry
for response in rsps.registry:  # or just iter(rsps.registry)
    ...
len(rsps.registry)
``` 

I could imagine to extend the interface to `collections.abc.MutableSequence`, so this object could become the return value of `RequestsMock.registered` without backward incompatibility, but in the current implementation, I just kept the previous behavior of giving excess to the private attribute `rsps.registry._responses`.
I could also imagine to add a `BaseRegistry`, but you already mentioned in #416, that you do not see necessity for it.

### CODE REVIEW

**Comment by carloshorn** [comment]
Just noticed that the `StrictOrderRegistry` would also solve #180, because there would not be a fallback response remaining in the registry.

**Comment by beliaev-maksim** [comment]
There is probably some misunderstanding, in #416 there is no leakage. Opposite to this PR, in #416 swapping of registry during test run is discouraged. User sets specific registry only for a single test or for a single context manager

**Comment by carloshorn** [comment]
No offense @beliaev-maksim, I do not think there is any misunderstanding. Your PR implements an equivalent solution as I stated in the update of https://github.com/getsentry/responses/pull/416#issuecomment-955033144. However, your PR has not been merged yet, so there must be some concern about the implementation. 
The idea of this PR is to start with a minimalistic implementation regarding the change of any public interface. 
I know that you were very careful about not breaking backwards compatibility, but any additional keyword argument or additional method adds complexity which could be discussed as separate feature in a separate PR, e.g. the change of the module level activation decorator.
I am not saying that I am against your ideas or your implementation. I am just trying to get this feature into the library, where I can only guess on what is missing or too much in your proposal. At the end, we are working for the same goal and I am just trying a new attempt with a different approach.

**Comment by markstory** [comment]
>  However, your PR has not been merged yet, so there must be some concern about the implementation.

I've been a bit short on time lately and haven't had a chance to go through this or #416 in depth yet as they are large changes. I'm hoping to get to that later this week.

**Comment by markstory** [comment]
Going to close this as #416 was merged.

**Pull request closed without merging**
