### PR TITLE
Support gzipped request.body in json_params_matcher

### PR DESCRIPTION
**Pull request by haakonvt**
I just discovered `matchers` (absolute lifesaver in concurrent tests), but I currently need to disable gzip for the tests since it isn't supported ootb.

Ltmk if there are additional changed/updates/changelog entries etc. you want me to create 😄

### CODE REVIEW

**Review by doctrino — APPROVED** [review]
Looks good to me

**Comment by markstory** [comment]
Looking good. There is an error from mypy that will need to be resolved before this can be merged.

> responses/matchers.py:132:52: error: Argument 1 to "decompress" has incompatible type "bytes | str"; expected "Buffer"  [arg-type]

**Comment by haakonvt** [comment]
> Looking good. There is an error from mypy that will need to be resolved before this can be merged.
> 
> > responses/matchers.py:132:52: error: Argument 1 to "decompress" has incompatible type "bytes | str"; expected "Buffer"  [arg-type]

That one surprised me, seems like mypy think the error can be raised after variable has been updated... I wasn't sure how you feel about `cast` in this codebase, so I changed a few `request_body` to `request.body` to help `mypy` understand.

**Comment by markstory** [comment]
Thank you 🎉

**Pull request merged**
