### PR TITLE
Get a call by method ans URL

### PR DESCRIPTION
**Pull request by paulnicolet**
Solves https://github.com/getsentry/responses/issues/546

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
I am not convinced that we need this extension. 

What is the exact issue you try to solve?

**Comment by paulnicolet** [comment]
Sûre, I tried to describe in the linked issue, but the idea is that accessing calls by index makes assertions on requests pretty hard to read and maintain IMO, especially when having a good number of those. 

- Using indices forces to think about calls order, while we might not care
- It's hard for the reader to build understand which call are we accessing with a simple index
- Adding new calls will make all the indices shift, which is a pain to maintain

The idea is to have an easy way to fetch a given call, that exposes clearly the intention.

**Comment by beliaev-maksim** [comment]
What is about using `matchers` to match request body?
https://github.com/getsentry/responses#matching-request-body-contents

**Comment by paulnicolet** [comment]
Indeed. I have two concerns with matchers:

- It's less explicit than assertions to express that we are testing the body
- I'm not sure it's possible to extract custom fixtures out of requests mocks. It's a pattern that can come handy with POST requests, to define global fixtures and use those fixtures in a bunch of tests across the codebase. Then, we want to explicitly test that this call has been made with a precise body depending on the context, which we cannot do using matchers.

**Comment by beliaev-maksim** [comment]
I still believe that this is achievable with `matchers`

Ideally, do a check by calls is less recommended compared to check by responses


I have some concerns with proposed implementation from this PR. Very often users use `re` to match (then it should be sorted here as well) and, also, returning calls by index in case of multiple matches returns us back to the same issue not giving any benefit 


If we can resolve the issue with existing functionality in a simple way, then I don't see a need to modify the code base

**Comment by paulnicolet** [comment]
Of course, my proposal arises from the fact that I was not completely happy with the existing tools. 

Fine, let me put some extra effort and see if I can solve my issues using matchers, if I cannot I'll come back later and try to convince harder, with a more robust PR if needed 😉

**Pull request closed without merging**
