### PR TITLE
meta(gha): Deploy workflow enforce-license-compliance.yml

### PR DESCRIPTION
**Pull request by chadwhitacre**
I are a bot, here to deploy [enforce-license-compliance.yml](https://github.com/getsentry/.github/blob/135d4e0f41194b0379a3d2220a9226a7a180dd5d/.github/workflows/enforce-license-compliance.yml). 🤖

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
Hi @chadwhitacre 
what does this action do?
what are the allowed license types?

**Comment by markstory** [comment]
Chad is out for a bit, but I have some context on this

> what does this action do?

The action will send project dependencies to Fossa for license compatibility checks.

>  what are the allowed license types?

Given that project is Apache2.0 only other liberal licenses (MIT, Apache2, LGPL, GPL2) will be allowed.

**Comment by beliaev-maksim** [comment]
@markstory 
thanks!
ok, makes sense!

not clear why the pipe fails. requests 2.0 uses Apache License, Version 2.0

**Comment by chadwhitacre** [comment]
→ #540

**Pull request closed without merging**
